In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# opening the file

In [3]:
df = pd.read_csv('mobile_price_range_data.csv')
df.head()

battery_power  blue  clock_speed  dual_sim  fc  four_g  int_memory  m_dep  \
0            842     0          2.2         0   1       0           7    0.6   
1           1021     1          0.5         1   0       1          53    0.7   
2            563     1          0.5         1   2       1          41    0.9   
3            615     1          2.5         0   0       0          10    0.8   
4           1821     1          1.2         0  13       1          44    0.6   

   mobile_wt  n_cores  ...  px_height  px_width   ram  sc_h  sc_w  talk_time  \
0        188        2  ...         20       756  2549     9     7         19   
1        136        3  ...        905      1988  2631    17     3          7   
2        145        5  ...       1263      1716  2603    11     2          9   
3        131        6  ...       1216      1786  2769    16     8         11   
4        141        2  ...       1208      1212  1411     8     2         15   

   three_g  touch_screen  wifi  price_range  
0        0             0     1            1  
1        1             1     0            2  
2        1             1     0            2  
3        1             0     0            2  
4        1             1     0            1  

[5 rows x 21 columns]

In [4]:
df.shape

(2000, 21)

In [5]:
# checking if any null value is present

In [6]:
df.isnull().sum() # no null value is present

battery_power    0
blue             0
clock_speed      0
dual_sim         0
fc               0
four_g           0
int_memory       0
m_dep            0
mobile_wt        0
n_cores          0
pc               0
px_height        0
px_width         0
ram              0
sc_h             0
sc_w             0
talk_time        0
three_g          0
touch_screen     0
wifi             0
price_range      0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 21 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   battery_power  2000 non-null   int64  
 1   blue           2000 non-null   int64  
 2   clock_speed    2000 non-null   float64
 3   dual_sim       2000 non-null   int64  
 4   fc             2000 non-null   int64  
 5   four_g         2000 non-null   int64  
 6   int_memory     2000 non-null   int64  
 7   m_dep          2000 non-null   float64
 8   mobile_wt      2000 non-null   int64  
 9   n_cores        2000 non-null   int64  
 10  pc             2000 non-null   int64  
 11  px_height      2000 non-null   int64  
 12  px_width       2000 non-null   int64  
 13  ram            2000 non-null   int64  
 14  sc_h           2000 non-null   int64  
 15  sc_w           2000 non-null   int64  
 16  talk_time      2000 non-null   int64  
 17  three_g        2000 non-null   int64  
 18  touch_sc

In [8]:
# splitting the 20% of data for test data and 80% for training data

In [9]:
 x = df[['battery_power',	'blue',	'clock_speed',	'dual_sim',	'fc',	'four_g',	'int_memory','m_dep',	'mobile_wt',	'n_cores', 'pc','px_height','px_width',	'ram','sc_h',	'sc_w',	'talk_time','three_g','touch_screen',	'wifi']]
y = df['price_range']


In [10]:
print(x.shape)
print(y.shape)

(2000, 20)
(2000,)


In [11]:
print(type(x))
print(type(y))

<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [12]:
# training data - ml model will be trained on trained data
# testing data - ml model trained on training data will be used to generated predictions on the test data

In [13]:
from sklearn.model_selection import train_test_split

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20)

In [15]:
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1600, 20)
(400, 20)
(1600,)
(400,)


In [16]:
# splitting is done

In [17]:
# now using logistic regression and predicting the price range

In [18]:
from sklearn.linear_model import LogisticRegression

In [19]:
m1 = LogisticRegression()

In [20]:
# predicted price range
m1.fit(x_train,y_train) # ml model will be trained on training data
ypred_m1 = m1.predict(x_test) # ml model trained on training data is used to generate the predictions on the test data
ypred_m1

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([2, 3, 3, 2, 2, 3, 1, 3, 2, 2, 1, 3, 1, 0, 0, 3, 0, 0, 2, 1, 1, 0,
       2, 1, 3, 2, 1, 2, 0, 1, 2, 2, 3, 3, 2, 0, 3, 2, 3, 0, 3, 3, 3, 3,
       2, 1, 3, 2, 3, 1, 0, 3, 3, 3, 1, 2, 1, 2, 2, 0, 3, 2, 0, 2, 1, 3,
       2, 1, 2, 1, 2, 0, 2, 2, 3, 0, 2, 1, 2, 3, 0, 2, 3, 2, 0, 0, 3, 3,
       2, 3, 3, 2, 0, 2, 0, 2, 3, 3, 3, 2, 3, 3, 3, 2, 2, 1, 2, 2, 1, 3,
       3, 2, 0, 0, 3, 3, 3, 3, 2, 3, 2, 0, 3, 3, 3, 0, 0, 1, 2, 2, 0, 0,
       1, 0, 0, 0, 2, 3, 1, 1, 0, 0, 0, 1, 3, 2, 0, 0, 1, 2, 3, 3, 0, 3,
       3, 1, 1, 3, 2, 1, 2, 2, 2, 1, 2, 3, 1, 1, 3, 1, 3, 0, 3, 2, 3, 1,
       0, 0, 3, 3, 0, 3, 2, 3, 2, 0, 0, 3, 0, 2, 0, 3, 3, 2, 2, 2, 1, 3,
       1, 1, 3, 3, 0, 0, 3, 0, 0, 3, 0, 1, 3, 0, 0, 0, 2, 1, 2, 3, 3, 2,
       3, 3, 3, 0, 0, 0, 2, 2, 0, 0, 1, 1, 3, 2, 2, 2, 3, 2, 2, 1, 3, 1,
       3, 0, 3, 3, 0, 1, 3, 3, 3, 2, 2, 1, 0, 0, 2, 3, 2, 1, 0, 1, 0, 0,
       3, 3, 1, 2, 0, 1, 3, 3, 1, 2, 1, 0, 3, 2, 3, 3, 3, 2, 0, 3, 3, 3,
       0, 1, 1, 1, 1, 2, 2, 2, 1, 3, 2, 3, 1, 3, 0,

In [21]:
#  checking  accuracy
print("training score",m1.score(x_train,y_train))
print("testing score",m1.score(x_test,y_test))

training score 0.645625
testing score 0.62


In [22]:
# Computing Confusion matrix and classification report for logisticregression model.


In [23]:
from sklearn.metrics import confusion_matrix,classification_report


In [24]:
cm = confusion_matrix(ypred_m1,y_test)

cm

array([[71, 16,  0,  0],
       [19, 48, 14,  1],
       [ 0, 27, 51, 28],
       [ 0,  9, 38, 78]])

In [25]:
print(classification_report(y_test,ypred_m1))

              precision    recall  f1-score   support

           0       0.82      0.79      0.80        90
           1       0.59      0.48      0.53       100
           2       0.48      0.50      0.49       103
           3       0.62      0.73      0.67       107

    accuracy                           0.62       400
   macro avg       0.63      0.62      0.62       400
weighted avg       0.62      0.62      0.62       400



In [26]:
# now using KNN classification and predicting the price range

In [27]:
from sklearn.neighbors import KNeighborsClassifier

In [28]:
m2 = KNeighborsClassifier(n_neighbors=11) #k=11
m2.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=11)

In [29]:
# predicted price range
ypred_m2 = m2.predict(x_test)
ypred_m2


array([1, 2, 2, 2, 3, 2, 1, 3, 2, 2, 0, 2, 2, 0, 0, 3, 0, 0, 3, 2, 1, 0,
       2, 1, 3, 3, 2, 2, 0, 0, 3, 2, 2, 3, 2, 0, 2, 2, 2, 0, 2, 3, 1, 1,
       1, 0, 3, 1, 3, 1, 0, 3, 3, 3, 1, 2, 2, 3, 1, 1, 3, 2, 1, 3, 1, 3,
       2, 2, 2, 3, 1, 0, 1, 2, 3, 0, 1, 2, 2, 2, 0, 2, 2, 2, 0, 0, 3, 3,
       3, 3, 3, 2, 0, 1, 0, 3, 2, 3, 3, 3, 1, 3, 3, 2, 1, 1, 3, 1, 0, 3,
       3, 1, 0, 0, 3, 2, 2, 2, 1, 2, 3, 1, 3, 1, 3, 0, 0, 1, 2, 3, 0, 0,
       1, 0, 0, 0, 1, 2, 1, 2, 0, 0, 1, 1, 3, 2, 0, 0, 1, 3, 1, 3, 0, 2,
       3, 1, 1, 3, 3, 1, 2, 2, 2, 1, 1, 2, 1, 1, 3, 0, 2, 0, 3, 2, 3, 0,
       0, 0, 2, 3, 0, 3, 2, 2, 3, 0, 0, 3, 0, 3, 0, 2, 3, 2, 2, 3, 0, 2,
       1, 1, 3, 2, 1, 0, 2, 0, 0, 3, 0, 1, 2, 1, 0, 0, 2, 0, 2, 3, 3, 2,
       2, 3, 3, 1, 0, 0, 1, 3, 0, 1, 0, 1, 1, 2, 3, 3, 3, 2, 3, 1, 3, 1,
       2, 0, 3, 2, 0, 0, 2, 3, 3, 1, 2, 0, 0, 1, 2, 1, 2, 1, 0, 1, 0, 0,
       3, 3, 0, 1, 0, 1, 3, 3, 0, 2, 1, 0, 2, 1, 3, 3, 2, 3, 0, 3, 3, 1,
       0, 1, 0, 1, 1, 3, 3, 2, 1, 3, 1, 3, 1, 1, 1,

In [30]:
#  checking  accuracy
print("training score",m2.score(x_train,y_train))
print("testing score",m2.score(x_test,y_test))

training score 0.94625
testing score 0.925


In [31]:
# Computing Confusion matrix and classification report for KNN classification model.


In [32]:
from sklearn.metrics import confusion_matrix,classification_report

In [33]:
cm_1 = confusion_matrix(ypred_m2,y_test)

cm_1

array([[89,  4,  0,  0],
       [ 1, 93,  7,  0],
       [ 0,  3, 89,  8],
       [ 0,  0,  7, 99]])

In [34]:
print(classification_report(y_test,ypred_m2))

              precision    recall  f1-score   support

           0       0.96      0.99      0.97        90
           1       0.92      0.93      0.93       100
           2       0.89      0.86      0.88       103
           3       0.93      0.93      0.93       107

    accuracy                           0.93       400
   macro avg       0.93      0.93      0.93       400
weighted avg       0.92      0.93      0.92       400



In [35]:
# now using SVM Classifier with linear and rbf kernel and predicting the price range

In [36]:
from sklearn.svm import SVC #support vector classifier

In [37]:

m3 = SVC(kernel= 'linear',C=1)
m3.fit(x_train,y_train)

SVC(C=1, kernel='linear')

In [38]:
# predicted price range
ypred_m3 = m3.predict(x_test)
print('ypred\n',ypred_m3)

ypred
 [1 2 3 2 3 2 1 3 2 2 1 2 2 1 0 3 0 0 3 2 2 0 2 1 3 3 2 2 0 0 3 2 2 3 2 0 2
 2 3 0 2 2 1 1 2 0 3 1 3 1 0 2 3 3 1 2 3 2 1 1 3 2 1 3 1 3 2 2 2 2 1 0 1 2
 2 0 1 1 2 3 0 2 2 2 0 0 3 3 3 3 3 2 0 1 0 3 2 3 3 3 1 3 3 2 2 1 3 1 0 3 3
 1 0 0 3 2 2 2 1 2 3 1 3 1 3 0 0 1 2 3 0 0 1 0 0 0 1 2 1 2 0 0 1 1 3 2 0 0
 1 3 1 3 0 2 3 1 1 3 3 1 2 2 2 1 1 2 1 1 3 0 2 0 3 2 3 0 0 0 2 3 0 3 2 2 3
 0 0 3 0 3 0 2 3 3 2 3 0 2 1 1 3 2 1 0 2 0 0 3 0 1 2 1 0 0 2 0 3 3 3 2 2 3
 3 1 0 0 1 3 0 1 0 1 1 2 2 3 3 2 3 1 3 1 2 0 3 3 0 0 2 2 3 1 2 0 0 1 2 1 2
 1 0 1 0 0 3 3 0 1 0 1 3 3 0 2 1 0 3 2 3 3 2 3 0 3 3 1 1 2 0 1 1 3 3 2 1 3
 1 3 1 1 1 3 1 3 1 3 1 2 3 2 0 2 3 3 3 3 2 3 2 1 3 2 1 0 2 2 3 1 3 3 2 3 1
 1 2 2 0 1 3 1 0 2 2 1 3 0 3 0 1 2 0 0 3 0 0 1 0 0 0 1 1 3 1 1 1 1 1 0 1 0
 1 1 2 2 2 1 2 0 2 0 3 2 0 3 3 1 0 1 0 0 1 0 3 1 1 3 2 1 1 2]


In [39]:
# checking  accuracy
print('training score',m3.score(x_train,y_train))
print('testing score',m3.score(x_test,y_test))


training score 0.99
testing score 0.98


In [40]:
# Computing Confusion matrix and classification report for SVM Classifier with linear and rbf kernel model.


In [41]:
# confusion matrix
cm_2 = confusion_matrix(ypred_m3,y_test)
cm_2

array([[ 90,   0,   0,   0],
       [  0,  98,   3,   0],
       [  0,   2,  98,   1],
       [  0,   0,   2, 106]])

In [42]:
# classification report
print(classification_report(y_test,ypred_m3))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        90
           1       0.97      0.98      0.98       100
           2       0.97      0.95      0.96       103
           3       0.98      0.99      0.99       107

    accuracy                           0.98       400
   macro avg       0.98      0.98      0.98       400
weighted avg       0.98      0.98      0.98       400

